### ISSUE TITLE
Windows XP & WC3Connect

### ISSUE THREAD

**Issue by ghost** [uakfdotb/wc3connect#10]
We have recently an issue with WC3Connect and Windows XP users:

![Screenshot](http://snag.gy/UUbTM.jpg)

What can be done to solve this?

**Comment by Profforgr** [comment]
Just checked this. Installed new virtual machine from some old Windows XP SP3 x86 iso, installed latest Java, reboot, set Java security to "Medium" (the lowest possible level), reboot, enter Google Chrome, open my website with wc3connect - click 'Accept' in popup window - and color turns to Green.

So i don't see any problems. Can you try to re-test with Google Chrome and/or try to reinstall Java?

**Comment by ghost** [comment]
Where you are running wc3connect web files?
So basically which OS? Our webserver is currently Windows, and I think this is creating the issue.

**Comment by Profforgr** [comment]
> Where you are running wc3connect web files?
> So basically which OS? Our webserver is currently Windows, and I think this is creating the issue.

My webserver is on Linux Debian Wheezy x64. I am not sure can Windows cause such issue, but you should switch to Linux anyway :)
