### ISSUE TITLE
windows isseue

### ISSUE THREAD

**Issue by styla01** [uakfdotb/wc3connect#6]
readline problem:  Note: This extension is not available on Windows platforms.
can someone help me with a compiled and working SWC3Connect.jar  ?

**Comment by JoseAmaru** [comment]
the same happens to me

**Comment by uakfdotb** [comment]
When do you get the "readline problem" message?

**Comment by uakfdotb** [comment]
If this happens when executing genkeystore.php or signer.php, open up the PHP files in a text editor (such as notepad) and replace each readline("...") with a value; like

$passphrase = "yourpassphrasehere";

**Comment by styla01** [comment]
tks for hint uakf, we are noobs
