### ISSUE TITLE
Error Wc3cd.jar

### ISSUE THREAD

**Issue by JoseAmaru** [uakfdotb/wc3connect#7]
http://prntscr.com/2drj8d

**Comment by uakfdotb** [comment]
Try using java -jar wc3cd.jar wc3cd.cfg instead.

**Comment by JoseAmaru** [comment]
does not work gives the same error
http://prntscr.com/2drrdv

**Comment by uakfdotb** [comment]
Probably you're using old version or the JAR in repository is outdated. Anyway just rename wc3cd.cfg to wc3connect.cfg.
