### ISSUE TITLE
i can.t connect from external IP

### ISSUE THREAD

**Issue by styla01** [uakfdotb/wc3connect#8]
my server with ghost bot,gcb and w3cconnect  have lan ip 192.168.1.5.
from  lan PC with internal 192.168.1.4 i can connect with w3cconnect, but when i try to connect from external ip 88.123.123.123 i can't :( can tell me a point where to search and fix it? (firewall is off and i forward the 6113 port)

**Comment by uakfdotb** [comment]
Go to MySQL and run this query:

`SELECT ipport FROM wc3connect_list;`

If you see your internal IP address, that's the problem -- when you connect from external IP it's trying to connect using the internal IP address. So, one solution is to edit net.entgaming.wc3connectd.WCServer, find the call to database.update, and replace packet.getAddress().getHostAddress() with "1.2.3.4", where 1.2.3.4 is the external IP address of the host bot.

**Comment by styla01** [comment]
omg is my internal ip: 192.168.1.5:6128
but the real problem is my dinamic IP,  can i use domain name? and omg i must install netbean again and learn again how to compile  :)
can u make it easy like in gcb? or to do 0.0.0.0 and accept all .....

**Comment by uakfdotb** [comment]
You do have to recompile it.

You can use your hostname, but you have to resolve it from WCServer. So try replacing it with InetAddress.getByName().getHostAddress()

**Comment by styla01** [comment]
this line: database.update(packet.getAddress().getHostAddress(), port, packetBytes);
will be 
database.update(InetAddress.getByName().getHostAddress(), port, packetBytes);
and i must complie both folders? wc3connectd and wc3connect ?

**Comment by styla01** [comment]
i need lib for them ? i can't compile...  tryed with "java project with existing sources"

**Comment by styla01** [comment]
finly i found but compile error:

error: cannot find symbol
                database.update(InetAddress.getByName().getHostAddress(), port, packetBytes);
                                ^
  symbol:   variable InetAddress
  location: class WCServer

**Comment by uakfdotb** [comment]
Use getByName("yourdomain.com")

**Comment by uakfdotb** [comment]
Also you need to add this to the top, where the imports are:

`import java.net.InetAddress;`

**Comment by styla01** [comment]
compiled and replaced WC3Connect but in data base still show internal ip ....

**Comment by styla01** [comment]
replaced the wc3cd.jar but still not work, process die...

**Comment by uakfdotb** [comment]
What do you mean process die?

**Comment by styla01** [comment]
this wc3cd.jar ,and i recompiled pure code and still same problem: wc3cd.jar cannot start , is somthing wrong with compilator ... and i dont have a log to check :(

**Comment by styla01** [comment]
[Config] Loading configuration file wc3cd.cfg
[WCServer] Got packet from 192.168.1.5:6137
[Database] Creating new connection...
[Database] Unable to connect to mysql database: No suitable driver found for jdb
c:mysql://localhost/wc3connect
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost/wc3co
nnect
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at net.entgaming.wc3connectd.Database.connection(Database.java:48)
        at net.entgaming.wc3connectd.Database.update(Database.java:109)
        at net.entgaming.wc3connectd.WCServer.run(WCServer.java:187)
[WCServer] Got packet from 192.168.1.5:6138

**Comment by uakfdotb** [comment]
Instead of making JAR file, try running these from src folder:

```
javac -classpath ../bin/lib/*:. net/entgaming/wc3connectd/WCServer.java
java -classpath ../bin/lib/*:. net.entgaming.wc3connectd.WCServer
```

**Comment by styla01** [comment]
seems to work now, i replaced "packet.getAddress().getHostAddress()"  with  "InetAddress.getByName("imy domain").getHostAddress()"  3 times and now show corectly in db, i will test more.

**Comment by styla01** [comment]
still not work, now its my external ip, but same issue: i can join only from my LAN :( can u do a test?

**Comment by uakfdotb** [comment]
That indicates that you have not set up port forwarding properly. Are you able to join from Battle.net or PVPGN or anywhere else?

**Comment by styla01** [comment]
yes, players and me,can join from GCB or  Battle.net or PVPGN there are no problems!
but they cant join from w3c, i am the only one who can join ( from local network with ip 192.168.1.4)

**Comment by uakfdotb** [comment]
So are you saying it still has the internal IP address?

**Comment by styla01** [comment]
no, is external ip adress now(after recompile and looks like 88.232.199.217:6137), but i can join only from my LAN.
gamenames hosted by bots in w3c are visible for all(external players ips +me), and the square is green,but like i said i can join only from my lan....
here is the link http://www.ingame.ro/wc3connect/

**Comment by uakfdotb** [comment]
Are you port forwarding 6137 -> 6137, or something else like 6112 -> 6137?

**Comment by uakfdotb** [comment]
Sorry, gave you the wrong code to change. Instead change this:

`buf.put(address); //IP address; this is not part of W3GS protocol but we add because it's required to connect`

to

`buf.put(InetAddress.getByName("example.com").getAddress()); //IP address; this is not part of W3GS protocol but we add because it's required to connect`

**Comment by styla01** [comment]
"Are you port forwarding 6137 -> 6137, or something else like 6112 -> 6137?" ofc is forwarded.

i will do last changes and i will be back

**Comment by styla01** [comment]
now it;s work!!! but idk why i have so many Anonymous :D probably phpbb issue
THANKS!
