### ISSUE TITLE
Small problem with broadcasting

### ISSUE THREAD

**Issue by ghost** [uakfdotb/wc3connect#9]
We have on our sever 3 new IP's, the primary one is .68, but not used currently by any bot.
The bots are bind to *.60 & *.133.

The problem is now on the database they are inserted with the *.68 IP.
Wc3Connect also says it receives the packets from *.68.

What is the issue here, is it relating to this comment: https://github.com/uakfdotb/wc3connect/issues/8#issuecomment-31324726 ?

GHost log also says that the IP is bind to *.60 on game start...

**Comment by Profforgr** [comment]
As uakf.b said, the best choice is to bind Ghost++ to all IP's.

**Comment by ghost** [comment]
The problem is, what will happen to the bnet connection?
User for it a hardcoded IP?

**Comment by Profforgr** [comment]
Do not change anything in bnet connection.

Just bind games on all IP's.

game_base.cpp ~157 line:

``` c++
    // start listening for connections

    /*if( !m_GHost->m_BindAddress.empty( ) )
        CONSOLE_Print( "[GAME: " + m_GameName + "] attempting to bind to address [" + m_GHost->m_BindAddress + "]" );
    else
        CONSOLE_Print( "[GAME: " + m_GameName + "] attempting to bind to all available addresses" );*/

    CONSOLE_Print( "[GAME: " + m_GameName + "] attempting to bind to all available addresses" );

    if( m_Socket->Listen( "", m_HostPort ) ) // m_GHost->m_BindAddress
        CONSOLE_Print( "[GAME: " + m_GameName + "] listening on port " + UTIL_ToString( m_HostPort ) );
    else
    {
        CONSOLE_Print( "[GAME: " + m_GameName + "] error listening on port " + UTIL_ToString( m_HostPort ) );
        m_Exiting = true;
    }
```

**Comment by ghost** [comment]
Yeap did it exactly like this now ;-)

Before you had time to paste it here :-)

Lets see ^^
